kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: routenet
nodes:
  - role: control-plane
    extraPortMappings:
      # Router service (NodePort 30080)
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # Inference service for debugging (NodePort 30081)
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
